// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8ujGjLfO3hgQh-TzgKJ9JT4GmsGhRDE',
    appId: '1:883209532428:web:7bb537cc12a5c5ecb1ea29',
    messagingSenderId: '883209532428',
    projectId: 'mobileproject-90352',
    authDomain: 'mobileproject-90352.firebaseapp.com',
    storageBucket: 'mobileproject-90352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtl-kzdtnFlsarqNrKlirSCi9hk7aJgbQ',
    appId: '1:883209532428:android:3a442e20cbbcd74fb1ea29',
    messagingSenderId: '883209532428',
    projectId: 'mobileproject-90352',
    storageBucket: 'mobileproject-90352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmB-jO0PAUsqOdOT1PxlMX2YifR9MGR0',
    appId: '1:883209532428:ios:7e737b2af8567247b1ea29',
    messagingSenderId: '883209532428',
    projectId: 'mobileproject-90352',
    storageBucket: 'mobileproject-90352.appspot.com',
    iosClientId: '883209532428-fkgcfuiroau69l638u2oi1vpfinjkanm.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurant',
  );
}
